baseURL = "https://hugo.thepavilion.io/"
languageCode = "en-us"
title = "Hugo - Pavilion"
theme = "ananke"

[server]

  [[server.headers]]
    for = "/**"

    [server.headers.values]
      Content-Security-Policy = "script-src localhost:1313 'unsafe-inline'"
      Access-Control-Allow-Origin = "*"